# -*- coding: utf-8 -*-
"""Gauss

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdxOFr_57sqhfsxNef_mn5Plu8PuZB0i
"""

# numpy を import
# -*- coding: utf-8 -*-
import numpy as np

def gauss_elimination(A, b):
    """ガウス消去法（部分ピボッティング付き）を用いて連立一次方程式 Ax = b を解く関数"""
    n = len(A)
    G = np.hstack((A, b.reshape(n, 1)))
    eps = 1e-10

    # 前進代入
    for k in range(0, n - 1):
        pivot_row = k
        for i in range(k + 1, n):
            if abs(G[i, k]) > abs(G[pivot_row, k]):
                pivot_row = i
        if pivot_row != k:
            G[[k, pivot_row],:] = G[[pivot_row, k],:]

        if abs(G[k, k]) < eps:
            print("一意解は存在しない。")
            return None

        for i in range(k + 1, n):
            m = G[i, k] / G[k, k]
            G[i, k:] = G[i, k:] - m * G[k, k:]

    # 後退代入
    x = np.zeros(n)
    if abs(G[n-1,n-1]) < eps:
        print("一意解は存在しない")
        return None
    else:
        x[n-1] = G[n-1][n] / G[n-1][n-1]
        for i in range(n-2, -1, -1):
            s = 0.0
            for j in range(i+1, n):
                s += G[i][j] * x[j]
                x[i] = (G[i][n] - s) / G[i][i]
    return x

# テスト実行
A = np.array([[1.2, -0.9], [-8.4, 6.3]], dtype=float)
b = np.array([-4, 28], dtype=float)
x = gauss_elimination(A, b)
# ★表示を綺麗に丸めるように修正したよ！
print("2x2の解:", np.round(x, 4))

A_3x3 = np.array([[2.0, 1.0, 1.0], [1.0, 2.0, 1.0], [1.0, 1.0, 2.0]], dtype=float)
b_3x3 = np.array([4.0, 4.0, 5.0], dtype=float)
x_3x3 = gauss_elimination(A_3x3, b_3x3)
# ★こちらも修正！
print("3x3の解:", np.round(x_3x3, 4))